version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: esportify_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esportify
      MYSQL_USER: esportify_user
      MYSQL_PASSWORD: esportify_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./SQL/insert_data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: esportify_app
    restart: always
    env_file:
      - .env
    environment:
        DB_URL: jdbc:mysql://db:3306/esportify
        DB_USER: ${ES_DB_USER}
        DB_PASSWORD: ${ES_DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
